In [3]:
import pandas as pd
import numpy as np

In [27]:
df = pd.read_excel("AllModels.xlsx")
df.head()

,No,sentence,GPT,GEMINI,DeepSeek,majority_vote
0,1,12-month ahead inflation expectations rose sli...,hawkish,hawkish,neutral,hawkish
1,2,1-month and 12 month exchange rate volatilitie...,neutral,neutral,neutral,neutral
2,3,24-month ahead inflation expectations remained...,neutral,hawkish,neutral,neutral
3,4,A backward-looking pricing behavior prevails i...,hawkish,hawkish,hawkish,hawkish
4,5,A critical underlying assumption for the infla...,neutral,hawkish,neutral,neutral

In [5]:
DisAgreeDf = df[((df["GPT"] != df["GEMINI"]) & 
                (df["GPT"] != df["DeepSeek"] )& 
                (df["GEMINI"] != df["DeepSeek"]))]
print(len(DisAgreeDf))
DisAgreeDf.head()

74

,No,sentence,GPT,GEMINI,DeepSeek,majority_vote
893,894,"Against this background, the Committee assesse...",hawkish,dovish,neutral,dovish
1158,1159,Although recently released data point to a str...,neutral,dovish,hawkish,dovish
1196,1197,Although the first-quarter rise in constructio...,neutral,dovish,hawkish,dovish
1903,1904,Another major risk to the inflation outlook is...,hawkish,dovish,neutral,dovish
2008,2009,"As a result, it is assessed that the uncertain...",hawkish,dovish,neutral,dovish

In [28]:
neutral_df = df[df["majority_vote"] == "neutral"].sample(n=120, random_state=42)
hawkish_df = df[df["majority_vote"] == "hawkish"].sample(n=120, random_state=42)
dovish_df  = df[df["majority_vote"] == "dovish"].sample(n=120, random_state=42)
balanced_df = pd.concat([neutral_df, hawkish_df, dovish_df]).sample(frac=1, random_state=42).reset_index(drop=True)

In [7]:
balanced_df.head()

,No,sentence,GPT,GEMINI,DeepSeek,majority_vote
0,1157,Although recent developments regarding importe...,hawkish,hawkish,neutral,hawkish
1,4465,Having a high tendency for backward indexation...,neutral,neutral,neutral,neutral
2,13482,The month-on-month increase in inflation expec...,dovish,dovish,neutral,dovish
3,11014,Should the goals set out in the MTP be impleme...,dovish,dovish,dovish,dovish
4,14282,The total effect of adjustments in certain pro...,neutral,neutral,neutral,neutral

In [8]:
balanced_df.to_excel("FewShotSentences.xlsx")

In [9]:
with open("FewShotSentences.txt", "w", encoding="utf-8") as f:
    f.write("\n".join(balanced_df["sentence"].astype(str)))

In [16]:
import google.generativeai as genai
import pandas as pd
import os

In [17]:
import os
os.environ["GOOGLE_API_KEY"] = "AIzaSyB7o3MQm4boXKx4zjg80TYXcGT1JQXaqTU"

In [18]:
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

In [ ]:
for m in genai.list_models():
    print(m.name)

In [20]:
model = genai.GenerativeModel("models/gemini-2.5-flash")

In [22]:
with open("FewShotSentences.txt", "r", encoding="utf-8") as file:
    sentences = [line.strip() for line in file if line.strip()]

print(len(sentences))
df = pd.DataFrame(sentences, columns=["sentence"])
df["label"] = ""


def classify_sentence(sentence):
    prompt = f"""
You are an expert in monetary policy communication.
Classify the following sentence from the Central Bank of the Republic of Turkey (CBRT)
based on its policy tone.

Below are some labeled examples provided for guidance.

Examples:

Sentence: "A revision in the monetary policy stance may be considered, should the fiscal stance deviate significantly from this framework and consequently have an adverse effect on inflation outlook."
Label: hawkish

Sentence: "A significant tightening in financial conditions has been achieved, following the monetary policy and liquidity management steps taken to contain inflation expectations and risks to the inflation outlook."
Label: hawkish

Sentence: "According to leading indicators, the exchange rate-led increases in many items in the inflation basket, durable consumption goods in particular, have started to be reflected on consumer inflation."
Label: hawkish

Sentence: "A decline in the underlying trend of monthly inflation is observed."
Label: dovish

Sentence: "A sustained fall in inflation and a sizable adjustment in the current account were achieved."
Label: dovish

Sentence: "Accordingly, annual inflation in core indicators is projected to fall further in the upcoming period."
Label: dovish

Sentence: "1-month and 12-month exchange rate volatilities of the Turkish lira declined 2.9 and 5.0 percentage points, respectively, in this MPC meeting period."
Label: neutral

Sentence: "A joint evaluation of all these developments reveals that banks’ loanable funds are on a rise."
Label: neutral

Sentence: "A similar outlook is also evident in demand indicators."
Label: neutral

Now classify the following sentence:

Sentence: "{sentence}"

Choose only one of the following labels:

- "hawkish": if the sentence signals inflationary pressure, interest rate hikes, tightening, or economic risks requiring policy action.
- "dovish": if the sentence signals easing, financial support, rate cuts, or declining inflation.
- "neutral": if the sentence is purely descriptive with no policy implications.

Return only the label as a single word: hawkish, dovish, or neutral.
"""

    try:
        response = model.generate_content(prompt)
        label = response.text.strip().lower()
        for valid_label in ["hawkish", "dovish", "neutral"]:
            if valid_label in label:
                return valid_label
        return "unknown"
    except Exception as e:
        print(f"Hata: {e}")
        return "hata"

360

In [23]:
df.shape

(360, 2)

In [24]:
import time
for idx, row in df.iterrows():
    label = classify_sentence(row["sentence"])
    df.at[idx, "label"] = label
    
    time.sleep(0.5)
    if idx % 50 == 0:
        try:
            df.to_excel("Gemini_Few_Shot_Partial.xlsx", index=False)
            print(f"{idx} cümle işlendi...")
            print("kayıt yapıldı")
        except:
            print(f"{idx} cümle işlendi...")
            print("kayıt yapılamadı.")

df.to_excel("Gemini_Few_Shot.xlsx", index=False)

0 cümle işlendi...
kayıt yapıldı
50 cümle işlendi...
kayıt yapıldı
100 cümle işlendi...
kayıt yapıldı
150 cümle işlendi...
kayıt yapıldı
200 cümle işlendi...
kayıt yapıldı
250 cümle işlendi...
kayıt yapıldı
300 cümle işlendi...
kayıt yapıldı
350 cümle işlendi...
kayıt yapıldı

In [26]:
df.head()

                                            sentence    label
0  Although recent developments regarding importe...  hawkish
1  Having a high tendency for backward indexation...   dovish
2  The month-on-month increase in inflation expec...   dovish
3  Should the goals set out in the MTP be impleme...   dovish
4  The total effect of adjustments in certain pro...  hawkish

In [28]:
from openai import OpenAI
import pandas as pd
import time
import random

In [29]:
import os
os.environ["OPENAI_API_KEY"] = "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"

In [30]:
client = OpenAI()

In [31]:
with open("FewShotSentences.txt", "r", encoding="utf-8") as file:
    sentences = [line.strip() for line in file if line.strip()]

# DataFrame oluştur
df = pd.DataFrame(sentences, columns=["sentence"])
df["label"] = ""

# Etiketleme fonksiyonu
def classify_sentence(sentence):
    prompt = f"""
You are an expert in monetary policy communication.
Classify the following sentence from the Central Bank of the Republic of Turkey (CBRT)
based on its policy tone.

Below are some labeled examples provided for guidance.

Examples:

Sentence: "A revision in the monetary policy stance may be considered, should the fiscal stance deviate significantly from this framework and consequently have an adverse effect on inflation outlook."
Label: hawkish

Sentence: "A significant tightening in financial conditions has been achieved, following the monetary policy and liquidity management steps taken to contain inflation expectations and risks to the inflation outlook."
Label: hawkish

Sentence: "According to leading indicators, the exchange rate-led increases in many items in the inflation basket, durable consumption goods in particular, have started to be reflected on consumer inflation."
Label: hawkish

Sentence: "A decline in the underlying trend of monthly inflation is observed."
Label: dovish

Sentence: "A sustained fall in inflation and a sizable adjustment in the current account were achieved."
Label: dovish

Sentence: "Accordingly, annual inflation in core indicators is projected to fall further in the upcoming period."
Label: dovish

Sentence: "1-month and 12-month exchange rate volatilities of the Turkish lira declined 2.9 and 5.0 percentage points, respectively, in this MPC meeting period."
Label: neutral

Sentence: "A joint evaluation of all these developments reveals that banks’ loanable funds are on a rise."
Label: neutral

Sentence: "A similar outlook is also evident in demand indicators."
Label: neutral

Now classify the following sentence:

Sentence: "{sentence}"

Choose only one of the following labels:

- "hawkish": if the sentence signals inflationary pressure, interest rate hikes, tightening, or economic risks requiring policy action.
- "dovish": if the sentence signals easing, financial support, rate cuts, or declining inflation.
- "neutral": if the sentence is purely descriptive with no policy implications.

Return only the label as a single word: hawkish, dovish, or neutral.
"""
    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
        )
        label = response.choices[0].message.content.strip().lower()
        return label

    except Exception as e:
        print(f"Hata: {e}")
        return "hata"

In [32]:
# Etiketleme döngüsü
for idx, row in df.iterrows():
    label = classify_sentence(row["sentence"])
    df.at[idx, "label"] = label
    time.sleep(0.5)

    if idx % 50 == 0:
        df.to_excel("GPT4-o_Few_Shot_Partial.xlsx", index=False)
        print(f"{idx} cümle işlendi...")


# Son kaydetme
df.to_excel("GPT4-o_Few_Shot.xlsx", index=False)

0 cümle işlendi...
50 cümle işlendi...
100 cümle işlendi...
150 cümle işlendi...
200 cümle işlendi...
250 cümle işlendi...
300 cümle işlendi...
350 cümle işlendi...

In [33]:
import requests
import pandas as pd
import time
from tqdm import tqdm  # Progress bar için

# DeepSeek API Ayarları
API_KEY = "sk-d9d5fb2a6cea4e2fb854cff5093a1e42"  # API keyinizi buraya girin
API_URL = "https://api.deepseek.com/v1/chat/completions"
HEADERS = {
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json"
}

In [35]:
# TXT dosyasından cümleleri oku
with open("FewShotSentences.txt", "r", encoding="utf-8") as file:
    sentences = [line.strip() for line in file if line.strip()]

# DataFrame oluştur
df = pd.DataFrame(sentences, columns=["sentence"])
df["label"] = ""

# Etiketleme fonksiyonu (DeepSeek uyumlu)
def classify_sentence(sentence):
    prompt = f"""
You are an expert in monetary policy communication.
Classify the following sentence from the Central Bank of the Republic of Turkey (CBRT)
based on its policy tone.

Below are some labeled examples provided for guidance.

Examples:

Sentence: "A revision in the monetary policy stance may be considered, should the fiscal stance deviate significantly from this framework and consequently have an adverse effect on inflation outlook."
Label: hawkish

Sentence: "A significant tightening in financial conditions has been achieved, following the monetary policy and liquidity management steps taken to contain inflation expectations and risks to the inflation outlook."
Label: hawkish

Sentence: "According to leading indicators, the exchange rate-led increases in many items in the inflation basket, durable consumption goods in particular, have started to be reflected on consumer inflation."
Label: hawkish

Sentence: "A decline in the underlying trend of monthly inflation is observed."
Label: dovish

Sentence: "A sustained fall in inflation and a sizable adjustment in the current account were achieved."
Label: dovish

Sentence: "Accordingly, annual inflation in core indicators is projected to fall further in the upcoming period."
Label: dovish

Sentence: "1-month and 12-month exchange rate volatilities of the Turkish lira declined 2.9 and 5.0 percentage points, respectively, in this MPC meeting period."
Label: neutral

Sentence: "A joint evaluation of all these developments reveals that banks’ loanable funds are on a rise."
Label: neutral

Sentence: "A similar outlook is also evident in demand indicators."
Label: neutral

Now classify the following sentence:

Sentence: "{sentence}"

Choose only one of the following labels:

- "hawkish": if the sentence signals inflationary pressure, interest rate hikes, tightening, or economic risks requiring policy action.
- "dovish": if the sentence signals easing, financial support, rate cuts, or declining inflation.
- "neutral": if the sentence is purely descriptive with no policy implications.

Return only the label as a single word: hawkish, dovish, or neutral.
"""
    
    payload = {
        "model": "deepseek-chat",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0,  # Deterministik sonuçlar için
        "max_tokens": 10
    }

    try:
        response = requests.post(API_URL, headers=HEADERS, json=payload)
        response.raise_for_status()
        
        # DeepSeek API yanıt formatı
        label = response.json()["choices"][0]["message"]["content"].strip().lower()
        
        # Sadece geçerli etiketleri kabul et
        if label in ["hawkish", "dovish", "neutral"]:
            return label
        else:
            print(f"Beklenmeyen yanıt: {label} | Cümle: {sentence}")
            return "error"
            
    except Exception as e:
        print(f"Hata: {e} | Cümle: {sentence}")
        return "error"

In [36]:
# İşlem ve kaydetme fonksiyonu
def process_and_save(df, batch_size=50, delay=0.5):
    for idx in tqdm(range(len(df)), desc="Etiketleniyor"):
        if df.at[idx, "label"] == "":  # Sadece boş olanları işle
            df.at[idx, "label"] = classify_sentence(df.at[idx, "sentence"])
            time.sleep(delay)  # Rate limit
            
            # Batch kaydet
            if (idx + 1) % batch_size == 0:
                df.to_excel("DeepSeek_Few_Shot_Partial.xlsx", index=False)
                print(f"\n{idx + 1} cümle işlendi. Ara kayıt yapıldı.")
    
    # Final kayıt
    df.to_excel("DeepSeek_Few_Shot.xlsx", index=False)
    print("Tüm işlem tamamlandı!")

# Çalıştır
if __name__ == "__main__":
    process_and_save(df)

Etiketleniyor:  14%|█▍        | 50/360 [01:26<08:50,  1.71s/it]

50 cümle işlendi. Ara kayıt yapıldı.

Etiketleniyor:  28%|██▊       | 100/360 [02:54<07:59,  1.84s/it]

100 cümle işlendi. Ara kayıt yapıldı.

Etiketleniyor:  42%|████▏     | 150/360 [04:20<06:00,  1.71s/it]

150 cümle işlendi. Ara kayıt yapıldı.

Etiketleniyor:  56%|█████▌    | 200/360 [05:48<05:14,  1.96s/it]

200 cümle işlendi. Ara kayıt yapıldı.

Etiketleniyor:  69%|██████▉   | 250/360 [07:17<03:14,  1.77s/it]

250 cümle işlendi. Ara kayıt yapıldı.

Etiketleniyor:  83%|████████▎ | 300/360 [08:44<01:44,  1.74s/it]

300 cümle işlendi. Ara kayıt yapıldı.

Etiketleniyor:  97%|█████████▋| 350/360 [10:13<00:18,  1.86s/it]

350 cümle işlendi. Ara kayıt yapıldı.

Etiketleniyor: 100%|██████████| 360/360 [10:30<00:00,  1.75s/it]

Tüm işlem tamamlandı!

In [21]:
FewshotGEMINI = pd.read_excel("Gemini_Few_Shot.xlsx")
FewshotGPT = pd.read_excel("GPT4-o_Few_Shot.xlsx")
FewshotDeepseek = pd.read_excel("DeepSeek_Few_Shot.xlsx")

In [22]:
balanced_df.head()

,No,sentence,GPT,GEMINI,DeepSeek,majority_vote,GEMINIFS,GPTFS,DeepSeekFS
0,1157,Although recent developments regarding importe...,hawkish,hawkish,neutral,hawkish,hawkish,hawkish,hawkish
1,4465,Having a high tendency for backward indexation...,neutral,neutral,neutral,neutral,dovish,neutral,neutral
2,13482,The month-on-month increase in inflation expec...,dovish,dovish,neutral,dovish,hawkish,dovish,dovish
3,11014,Should the goals set out in the MTP be impleme...,dovish,dovish,dovish,dovish,hawkish,dovish,dovish
4,14282,The total effect of adjustments in certain pro...,neutral,neutral,neutral,neutral,hawkish,neutral,neutral

In [29]:
balanced_df["GEMINIFS"] = FewshotGEMINI["label"]
balanced_df["GPTFS"] = FewshotGPT["label"]
balanced_df["DeepSeekFS"] = FewshotDeepseek["label"]
balanced_df.head()

,No,sentence,GPT,GEMINI,DeepSeek,majority_vote,GEMINIFS,GPTFS,DeepSeekFS
0,1157,Although recent developments regarding importe...,hawkish,hawkish,neutral,hawkish,hawkish,hawkish,hawkish
1,4465,Having a high tendency for backward indexation...,neutral,neutral,neutral,neutral,dovish,neutral,neutral
2,13482,The month-on-month increase in inflation expec...,dovish,dovish,neutral,dovish,hawkish,dovish,dovish
3,11014,Should the goals set out in the MTP be impleme...,dovish,dovish,dovish,dovish,hawkish,dovish,dovish
4,14282,The total effect of adjustments in certain pro...,neutral,neutral,neutral,neutral,hawkish,neutral,neutral

In [24]:
import krippendorff
LLMS = ["GPT", "GEMINI", "DeepSeek"]

for llm in LLMS:

    df = balanced_df[[llm, llm+"FS"]]

    SameLabelRatio = len(df[df[llm] == df[llm+"FS"]]) / len(df)
    data = [
        balanced_df[llm].tolist(),
        balanced_df[llm+"FS"].tolist()
        ]

    alpha = krippendorff.alpha(
        reliability_data=data,
        level_of_measurement='nominal'
    )
    print(f"{llm} Zero Shot - Few Shot % Result: {round(SameLabelRatio,4)} ")
    print(f"{llm} Zero Shot - Few Shot krippendorff_alpha Result: {round(alpha,4)}")

GPT Zero Shot - Few Shot % Result: 0.8694
GPT Zero Shot - Few Shot krippendorff_alpha Result: 0.8041
GEMINI Zero Shot - Few Shot % Result: 0.0639
GEMINI Zero Shot - Few Shot krippendorff_alpha Result: -0.1557
DeepSeek Zero Shot - Few Shot % Result: 0.7639
DeepSeek Zero Shot - Few Shot krippendorff_alpha Result: 0.613

In [10]:
import krippendorff
import pandas as pd

data = [
    balanced_df['DeepSeek'].tolist(),
    balanced_df['DeepSeekFS'].tolist()
]

alpha = krippendorff.alpha(
    reliability_data=data,
    level_of_measurement='nominal'
)

print(round(alpha, 4))

0.613

In [38]:
from collections import Counter

# FS_majority_Vote sütunu oluştur - GEMINIFS, GPTFS, DeepSeekFS'in majority vote'ı
def get_majority_vote(geminifs, gptfs, deepseekfs):
    """
    3 labeldan majority vote al.
    Eğer hepsi farklı ise GPTFS'yi seç.
    """
    if geminifs != gptfs and gptfs != deepseekfs and geminifs != deepseekfs:
        # Hepsi farklı - GPTFS'yi seç
        return gptfs
    else:
        # Majority vote
        counter = Counter([geminifs, gptfs, deepseekfs])
        return counter.most_common(1)[0][0]

balanced_df['FS_majority_Vote'] = balanced_df.apply(
    lambda row: get_majority_vote(row['GEMINIFS'], row['GPTFS'], row['DeepSeekFS']),
    axis=1
)

print("FS_majority_Vote sütunu başarıyla oluşturuldu!")
print(f"\nFS_majority_Vote Dağılımı:")
print(balanced_df['FS_majority_Vote'].value_counts())
print(f"\nİlk 5 satır:")
print(balanced_df[['sentence', 'GEMINIFS', 'GPTFS', 'DeepSeekFS', 'FS_majority_Vote']].head())

FS_majority_Vote sütunu başarıyla oluşturuldu!

FS_majority_Vote Dağılımı:
FS_majority_Vote
hawkish    133
neutral    126
dovish     101
Name: count, dtype: int64

İlk 5 satır:
                                            sentence GEMINIFS    GPTFS  \
0  Although recent developments regarding importe...  hawkish  hawkish
1  Having a high tendency for backward indexation...   dovish  neutral
2  The month-on-month increase in inflation expec...  hawkish   dovish
3  Should the goals set out in the MTP be impleme...  hawkish   dovish
4  The total effect of adjustments in certain pro...  hawkish  neutral

  DeepSeekFS FS_majority_Vote
0    hawkish          hawkish
1    neutral          neutral
2     dovish           dovish
3     dovish           dovish
4    neutral          neutral

In [39]:
import krippendorff

# majority_vote (Zero-shot) vs FS_majority_Vote (Few-shot) - Krippendorff's Alpha
data = [
    balanced_df['majority_vote'].tolist(),
    balanced_df['FS_majority_Vote'].tolist()
]

alpha = krippendorff.alpha(
    reliability_data=data,
    level_of_measurement='nominal'
)

# Aynı etiket yüzdesi
same_vote = len(balanced_df[balanced_df['majority_vote'] == balanced_df['FS_majority_Vote']]) / len(balanced_df)

print("=" * 70)
print("ZERO-SHOT MAJORITY VOTE vs FEW-SHOT MAJORITY VOTE - KRIPPENDORFF'S ALPHA")
print("=" * 70)
print(f"\nToplam Cümle Sayısı: {len(balanced_df)}")
print(f"Aynı Majority Vote Oranı: {round(same_vote * 100, 2)}%")
print(f"Farklı Majority Vote Sayısı: {len(balanced_df[balanced_df['majority_vote'] != balanced_df['FS_majority_Vote']])}")
print(f"\n🎯 Krippendorff's Alpha: {round(alpha, 4)}")

# Yorumlama
print("\n" + "=" * 70)
print("YORUMLAMA:")
print("=" * 70)
if alpha >= 0.81:
    print("✓ MÜKEMMEL Uyum (Perfect Agreement)")
elif alpha >= 0.67:
    print("✓ İYİ Uyum (Good Agreement)")
elif alpha >= 0.54:
    print("⚠ ORTA Uyum (Fair Agreement)")
else:
    print("✗ ZAYIF Uyum (Poor Agreement)")

# Detaylı karşılaştırma
print("\n" + "=" * 70)
print("KATEGORİ BAZINDA KARŞILAŞTIRMA:")
print("=" * 70)

for category in ['hawkish', 'dovish', 'neutral']:
    zero_shot = len(balanced_df[balanced_df['majority_vote'] == category])
    few_shot = len(balanced_df[balanced_df['FS_majority_Vote'] == category])
    agreement = len(balanced_df[(balanced_df['majority_vote'] == category) & 
                                (balanced_df['FS_majority_Vote'] == category)])
    
    print(f"\n{category.upper()}:")
    print(f"  Zero-shot count: {zero_shot}")
    print(f"  Few-shot count: {few_shot}")
    print(f"  Agreement: {agreement}")
    if zero_shot > 0:
        print(f"  Agreement %: {round(agreement / zero_shot * 100, 2)}%")

# Farklı etiketlendirilen örnekler
print("\n" + "=" * 70)
print("FARKLIL EĞİŞEN ÖRNEKLERİN ÖRNEKLERİ (İlk 10):")
print("=" * 70)

disagreement = balanced_df[balanced_df['majority_vote'] != balanced_df['FS_majority_Vote']]
print(f"\nToplam Farklı Etiketlendirme: {len(disagreement)}")

if len(disagreement) > 0:
    print("\nÖrnekler:")
    for idx, row in disagreement.head(10).iterrows():
        print(f"\nSatır {idx}: {row['sentence'][:70]}...")
        print(f"  Zero-shot majority: {row['majority_vote']}")
        print(f"  Few-shot majority: {row['FS_majority_Vote']}")
        print(f"  Individual predictions - Zero: GPT={row['GPT']}, GEMINI={row['GEMINI']}, DeepSeek={row['DeepSeek']}")
        print(f"  Individual predictions - Few:  GPT={row['GPTFS']}, GEMINI={row['GEMINIFS']}, DeepSeek={row['DeepSeekFS']}")

======================================================================
ZERO-SHOT MAJORITY VOTE vs FEW-SHOT MAJORITY VOTE - KRIPPENDORFF'S ALPHA
======================================================================

Toplam Cümle Sayısı: 360
Aynı Majority Vote Oranı: 87.78%
Farklı Majority Vote Sayısı: 44

🎯 Krippendorff's Alpha: 0.8166

======================================================================
YORUMLAMA:
======================================================================
✓ MÜKEMMEL Uyum (Perfect Agreement)

======================================================================
KATEGORİ BAZINDA KARŞILAŞTIRMA:
======================================================================

HAWKISH:
  Zero-shot count: 120
  Few-shot count: 133
  Agreement: 114
  Agreement %: 95.0%

DOVISH:
  Zero-shot count: 120
  Few-shot count: 101
  Agreement: 99
  Agreement %: 82.5%

NEUTRAL:
  Zero-shot count: 120
  Few-shot count: 126
  Agreement: 103
  Agreement %: 85.83%

======================================================================
FARKLIL EĞİŞEN ÖRNEKLERİN ÖRNEKLERİ (İlk 10):
======================================================================

Toplam Farklı Etiketlendirme: 44

Örnekler:

Satır 19: The labor market outlook continued to deteriorate in August due to slu...
  Zero-shot majority: dovish
  Few-shot majority: neutral
  Individual predictions - Zero: GPT=dovish, GEMINI=dovish, DeepSeek=neutral
  Individual predictions - Few:  GPT=neutral, GEMINI=dovish, DeepSeek=neutral

Satır 24: These developments are expected to have a limited effect on end-2014 i...
  Zero-shot majority: dovish
  Few-shot majority: neutral
  Individual predictions - Zero: GPT=dovish, GEMINI=dovish, DeepSeek=neutral
  Individual predictions - Few:  GPT=neutral, GEMINI=hawkish, DeepSeek=dovish

Satır 30: Recent data indicate that economic activity has continued to slow down...
  Zero-shot majority: dovish
  Few-shot majority: neutral
  Individual predictions - Zero: GPT=dovish, GEMINI=dovish, DeepSeek=neutral
  Individual predictions - Few:  GPT=neutral, GEMINI=hawkish, DeepSeek=neutral

Satır 46: The steep increase in vegetable prices due to adverse weather conditio...
  Zero-shot majority: neutral
  Few-shot majority: hawkish
  Individual predictions - Zero: GPT=neutral, GEMINI=hawkish, DeepSeek=neutral
  Individual predictions - Few:  GPT=hawkish, GEMINI=hawkish, DeepSeek=hawkish

Satır 50: Yet, the Committee assessed that readings on inflation do not present ...
  Zero-shot majority: dovish
  Few-shot majority: neutral
  Individual predictions - Zero: GPT=dovish, GEMINI=dovish, DeepSeek=neutral
  Individual predictions - Few:  GPT=neutral, GEMINI=hawkish, DeepSeek=neutral

Satır 55: The considerable fall in volatility in global financial markets and th...
  Zero-shot majority: dovish
  Few-shot majority: neutral
  Individual predictions - Zero: GPT=dovish, GEMINI=dovish, DeepSeek=neutral
  Individual predictions - Few:  GPT=neutral, GEMINI=dovish, DeepSeek=neutral

Satır 57: In light of these developments, the Committee has assessed that meetin...
  Zero-shot majority: neutral
  Few-shot majority: hawkish
  Individual predictions - Zero: GPT=neutral, GEMINI=neutral, DeepSeek=hawkish
  Individual predictions - Few:  GPT=hawkish, GEMINI=dovish, DeepSeek=hawkish

Satır 65: The weakening effects of geopolitical risks on global economic activit...
  Zero-shot majority: neutral
  Few-shot majority: hawkish
  Individual predictions - Zero: GPT=neutral, GEMINI=neutral, DeepSeek=neutral
  Individual predictions - Few:  GPT=hawkish, GEMINI=hawkish, DeepSeek=neutral

Satır 70: In crude oil markets, where a volatile course prevails, prices have in...
  Zero-shot majority: hawkish
  Few-shot majority: neutral
  Individual predictions - Zero: GPT=hawkish, GEMINI=hawkish, DeepSeek=neutral
  Individual predictions - Few:  GPT=neutral, GEMINI=dovish, DeepSeek=neutral

Satır 84: The recent trend in oil prices indicates two-way risks, with the downs...
  Zero-shot majority: dovish
  Few-shot majority: neutral
  Individual predictions - Zero: GPT=dovish, GEMINI=dovish, DeepSeek=neutral
  Individual predictions - Few:  GPT=neutral, GEMINI=nan, DeepSeek=neutral

In [1]:
import pandas as pd

In [2]:
s = pd.Series([1,2,3,4,5], name = "inflation")
print(s)

0    1
1    2
2    3
3    4
4    5
Name: inflation, dtype: int64

In [4]:
print(s.values)

[1 2 3 4 5]

In [25]:
# Zero-shot ve Few-shot Majority Vote Karşılaştırması - Krippendorff's Alpha
from scipy.stats import mode
import krippendorff

# Zero-shot majority vote hesapla
def get_majority_vote(gpt, gemini, deepseek):
    """3 LLM labelından majority vote al"""
    labels = [gpt, gemini, deepseek]
    most_common = mode(labels, keepdims=True).mode[0]
    return most_common

# Zero-shot majority vote
balanced_df['zero_shot_majority'] = balanced_df.apply(
    lambda row: get_majority_vote(row['GPT'], row['GEMINI'], row['DeepSeek']),
    axis=1
)

# Few-shot majority vote
balanced_df['few_shot_majority'] = balanced_df.apply(
    lambda row: get_majority_vote(row['GPTFS'], row['GEMINIFS'], row['DeepSeekFS']),
    axis=1
)

print("=" * 60)
print("ZERO-SHOT vs FEW-SHOT MAJORITY VOTE KARŞILAŞTIRMASI")
print("=" * 60)

# Krippendorff's Alpha hesapla
data = [
    balanced_df['zero_shot_majority'].tolist(),
    balanced_df['few_shot_majority'].tolist()
]

alpha = krippendorff.alpha(
    reliability_data=data,
    level_of_measurement='nominal'
)

# Aynı cevap yüzdesi
same_label_ratio = len(balanced_df[balanced_df['zero_shot_majority'] == balanced_df['few_shot_majority']]) / len(balanced_df)

print(f"\nToplam Cümle Sayısı: {len(balanced_df)}")
print(f"Aynı Etiket Oranı: {round(same_label_ratio * 100, 2)}%")
print(f"Farklı Etiket Sayısı: {len(balanced_df[balanced_df['zero_shot_majority'] != balanced_df['few_shot_majority']])}")
print(f"\nKrippendorff's Alpha: {round(alpha, 4)}")

# Detaylı analiz
print("\n" + "=" * 60)
print("DETAYLI ANALIZ")
print("=" * 60)

# Label dağılımı
print("\nZero-Shot Majority Vote Dağılımı:")
print(balanced_df['zero_shot_majority'].value_counts())

print("\nFew-Shot Majority Vote Dağılımı:")
print(balanced_df['few_shot_majority'].value_counts())

# Farklılıklar
disagreement_df = balanced_df[balanced_df['zero_shot_majority'] != balanced_df['few_shot_majority']][
    ['sentence', 'GPT', 'GEMINI', 'DeepSeek', 'GPTFS', 'GEMINIFS', 'DeepSeekFS', 'zero_shot_majority', 'few_shot_majority']
]

print(f"\nFarklı Etiketlendirilen Cümleler ({len(disagreement_df)}):")
print(disagreement_df.head(10))

# Her kategori için detay
print("\n" + "=" * 60)
print("KATEGORİ BAZINDA Agreement")
print("=" * 60)

for category in ['hawkish', 'dovish', 'neutral']:
    category_data = balanced_df[balanced_df['zero_shot_majority'] == category]
    if len(category_data) > 0:
        agreement = len(category_data[category_data['few_shot_majority'] == category]) / len(category_data)
        print(f"{category.upper()}: {len(category_data)} cümle, Agreement: {round(agreement * 100, 2)}%")

DTypePromotionError: The DType <class 'numpy._FloatAbstractDType'> could not be promoted by <class 'numpy.dtypes.StrDType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.StrDType'>, <class 'numpy._FloatAbstractDType'>)